import { ChapterMeta } from './types';

export const YOGA_CHAPTERS_META: Record<number, ChapterMeta> = {
    1: {
        chapter: 1,
        name_korean: '아르주나의 고뇌',
        name_english: 'Arjuna’s Dilemma',
        description: '전쟁터에서 흔들리는 마음과 첫 질문을 다룬다.',
        sutraCount: 35,
    },
    2: {
        chapter: 2,
        name_korean: '지혜의 길',
        name_english: 'Path of Knowledge',
        description: '행동과 지혜의 기본을 세우는 장이다.',
        sutraCount: 71,
    },
    3: {
        chapter: 3,
        name_korean: '행동의 길',
        name_english: 'Path of Action',
        description: '무욕의 행동과 책임 있는 삶을 설명한다.',
        sutraCount: 41,
    },
    4: {
        chapter: 4,
        name_korean: '지혜와 해탈의 결합',
        name_english: 'Knowledge and Liberation',
        description: '지혜가 행동과 만날 때의 깊이를 다룬다.',
        sutraCount: 41,
    },
    5: {
        chapter: 5,
        name_korean: '행동의 포기',
        name_english: 'Renunciation of Action',
        description: '행동을 버리는 것이 아니라 집착을 비우는 길이다.',
        sutraCount: 27,
    },
    6: {
        chapter: 6,
        name_korean: '마음의 훈련',
        name_english: 'Discipline of Mind',
        description: '마음을 다스리고 흔들림을 줄이는 수행을 다룬다.',
        sutraCount: 44,
    },
    7: {
        chapter: 7,
        name_korean: '지식과 통찰',
        name_english: 'Knowledge and Wisdom',
        description: '현상 세계와 그 너머를 함께 본다.',
        sutraCount: 30,
    },
    8: {
        chapter: 8,
        name_korean: '불멸의 길',
        name_english: 'The Imperishable',
        description: '죽음과 초월, 최후의 기억을 다룬다.',
        sutraCount: 23,
    },
    9: {
        chapter: 9,
        name_korean: '왕의 비밀',
        name_english: 'Royal Knowledge',
        description: '가장 깊은 비밀과 가장 단순한 신뢰를 전한다.',
        sutraCount: 32,
    },
    10: {
        chapter: 10,
        name_korean: '신성한 현현',
        name_english: 'Divine Glories',
        description: '신성의 다양한 드러남을 보여준다.',
        sutraCount: 39,
    },
    11: {
        chapter: 11,
        name_korean: '우주적 형상',
        name_english: 'Cosmic Vision',
        description: '절대자의 거대한 모습이 펼쳐진다.',
        sutraCount: 50,
    },
    12: {
        chapter: 12,
        name_korean: '헌신의 길',
        name_english: 'Path of Devotion',
        description: '사랑과 헌신이 수행이 되는 장이다.',
        sutraCount: 16,
    },
    13: {
        chapter: 13,
        name_korean: '장과 앎',
        name_english: 'Field and Knower',
        description: '몸과 의식, 앎의 구조를 해부한다.',
        sutraCount: 31,
    },
    14: {
        chapter: 14,
        name_korean: '세 가지 성향',
        name_english: 'Three Gunas',
        description: '자연을 이루는 세 성질의 작동을 설명한다.',
        sutraCount: 21,
    },
    15: {
        chapter: 15,
        name_korean: '궁극의 인격',
        name_english: 'Supreme Person',
        description: '현상 세계를 넘어선 궁극의 존재를 가리킨다.',
        sutraCount: 19,
    },
    16: {
        chapter: 16,
        name_korean: '신성한 성품과 비신성한 성품',
        name_english: 'Divine and Demoniac',
        description: '삶을 밝히는 힘과 흐리는 힘을 대비한다.',
        sutraCount: 19,
    },
    17: {
        chapter: 17,
        name_korean: '믿음의 세 가지 결',
        name_english: 'Threefold Faith',
        description: '믿음이 어떻게 세 가지 성향으로 드러나는지 본다.',
        sutraCount: 26,
    },
    18: {
        chapter: 18,
        name_korean: '해탈과 내려놓음',
        name_english: 'Liberation and Renunciation',
        description: '모든 가르침을 다시 묶어 해탈의 길로 정리한다.',
        sutraCount: 75,
    },
};
